### ISSUE TITLE
uninitialized constant Monologue::PostsRevision

### ISSUE THREAD

**Issue by International** [jipiboily/monologue-markdown#4]
This exception happens when running migrations. I'd say it's related to this file:

https://github.com/jipiboily/monologue/blob/master/app/models/monologue/posts_revision.rb.tmp

**Comment by jipiboily** [comment]
Are you running on Monologue's master branch? If yes, @msevestre remove revisions there, per our discussions and `monologue-markdown` does not support yet Monologue's master.

**Comment by International** [comment]
Yes, I was running on master. My bad.

**Comment by jipiboily** [comment]
If you want to run on master, feel free to create a PR here to remove revisions. ;)

I don't know when I'll have time to do it myself.

**Comment by jipiboily** [comment]
I updated monologue-markdown's master to work with https://github.com/jipiboily/monologue/tree/0-3-stable which is almost ready FYI.

**Comment by jipiboily** [comment]
Closing for now, as there is now another issue for this which is #5.
